import {default as Component} from "./ui/Component"
import type VirtualElement from './ui/VirtualElement'

export type DefaultComponentProps = {
    ref?: string
    class?: string
}

export type SubstanceCreateElement = <T>(elementStringOrComponent: typeof Component | string, componentProps?: T | DefaultComponentProps) => VirtualElement

/**
 * ---------------------------------------------------------------------------------
 *                    This file exports everything substance does
 *                              Probably don't touch it
 * ---------------------------------------------------------------------------------
 */
export {default as ChangeStore} from "./collab/ChangeStore"
export {default as ClientConnection} from "./collab/ClientConnection"
export {default as CollabClient} from "./collab/CollabClient"
export {default as CollabEngine} from "./collab/CollabEngine"
export {default as CollabServer} from "./collab/CollabServer"
export {default as CollabSession} from "./collab/CollabSession"
export {default as DocumentClient} from "./collab/DocumentClient"
export {default as DocumentEngine} from "./collab/DocumentEngine"
export {default as DocumentServer} from "./collab/DocumentServer"
export {default as SnapshotEngine} from "./collab/SnapshotEngine"
export {default as SnapshotStore} from "./collab/SnapshotStore"
export {default as WebSocketConnection} from "./collab/WebSocketConnection"
export {default as CollabServerConfigurator} from "./collab/CollabServerConfigurator"
export {default as CollabServerPackage} from "./collab/CollabServerPackage"
export {default as annotationHelpers} from "./model/annotationHelpers"
export {default as markersHelpers} from "./model/markersHelpers"
export {default as BlockNode} from "./model/BlockNode"
export {default as Container} from "./model/Container"
export {default as ContainerAnnotation} from "./model/ContainerAnnotation"
export {default as PropertyAnnotation} from "./model/PropertyAnnotation"
export {default as Data} from "./model/data/Data"
export {default as Document} from "./model/Document"
export {default as DocumentChange} from "./model/DocumentChange"
export {default as documentHelpers} from "./model/documentHelpers"
export {default as DocumentIndex} from "./model/DocumentIndex"
export {default as DocumentNode} from "./model/DocumentNode"
export {default as Editing} from "./model/Editing"
export {default as EditorSession} from "./model/EditorSession"
export {default as DOMExporter} from "./model/DOMExporter"
export {default as DOMImporter} from "./model/DOMImporter"
export {default as FileManager} from "./model/FileManager"
export {default as FileProxy} from "./model/FileProxy"
export {default as Fragmenter} from "./model/Fragmenter"
export {default as HTMLExporter} from "./model/HTMLExporter"
export {default as HTMLImporter} from "./model/HTMLImporter"
export {default as InlineNode} from "./model/InlineNode"
export {default as JSONConverter} from "./model/JSONConverter"
export {default as Marker} from "./model/Marker"
export {default as NodeIndex} from "./model/data/NodeIndex"
export {default as TextBlock} from "./model/TextBlock"
export {default as TextNode} from "./model/TextNode"
export {default as Selection} from "./model/Selection"
export {default as XMLExporter} from "./model/XMLExporter"
export {default as XMLImporter} from "./model/XMLImporter"
export {default as Transaction} from "./model/Transaction"
export {default as BasePackage} from "./packages/base/BasePackage"
export {default as BlockquotePackage} from "./packages/blockquote/BlockquotePackage"
export {default as ButtonPackage} from "./packages/button/ButtonPackage"
export {default as CodePackage} from "./packages/code/CodePackage"
export {default as CodeblockPackage} from "./packages/codeblock/CodeblockPackage"
export {default as EmphasisPackage} from "./packages/emphasis/EmphasisPackage"
export {default as ImagePackage} from "./packages/image/ImagePackage"
export {default as InlineWrapperPackage} from "./packages/inline-wrapper/InlineWrapperPackage"
export {default as OverlayPackage} from "./packages/overlay/OverlayPackage"
export {default as ParagraphPackage} from "./packages/paragraph/ParagraphPackage"
export {default as PersistencePackage} from "./packages/persistence/PersistencePackage"
export {default as StrongPackage} from "./packages/strong/StrongPackage"
export {default as SubscriptPackage} from "./packages/subscript/SubscriptPackage"
export {default as SuperscriptPackage} from "./packages/superscript/SuperscriptPackage"
export {default as FilePackage} from "./packages/file/FilePackage"
export {default as FileNode} from "./packages/file/FileNode"
export {default as HeadingPackage} from "./packages/heading/HeadingPackage"
export {default as HeadingMacro} from "./packages/heading/HeadingMacro"
export {default as SwitchTextTypeTool} from "./packages/switch-text-type/SwitchTextTypeTool"
export {default as SwitchTextTypeCommand} from "./packages/switch-text-type/SwitchTextTypeCommand"
export {default as SwitchTextTypePackage} from "./packages/switch-text-type/SwitchTextTypePackage"
export {default as ProseEditorPackage} from "./packages/prose-editor/ProseEditorPackage"
export {default as ProseEditor} from "./packages/prose-editor/ProseEditor"
export {default as ProseArticle} from "./packages/prose-editor/ProseArticle"
export {default as LinkPackage} from "./packages/link/LinkPackage"
export {default as EditLinkTool} from "./packages/link/EditLinkTool"
export {default as Link} from "./packages/link/Link"
export {default as LinkCommand} from "./packages/link/LinkCommand"
export {default as LinkComponent} from "./packages/link/LinkComponent"
export {default as TablePackage} from "./packages/table/TablePackage"
export {default as Table} from "./packages/table/Table"
export {default as TableCell} from "./packages/table/TableCell"
export {default as InsertInlineNodeCommand} from "./packages/inline-node/InsertInlineNodeCommand"
export {default as EditInlineNodeCommand} from "./packages/inline-node/EditInlineNodeCommand"
export {default as InlineNodeComponent} from "./packages/inline-node/InlineNodeComponent"
export {default as Button} from "./packages/button/Button"
export {default as ScrollPanePackage} from "./packages/scroll-pane/ScrollPanePackage"
export {default as ScrollPane} from "./packages/scroll-pane/ScrollPane"
export {default as BodyScrollPanePackage} from "./packages/body-scroll-pane/BodyScrollPanePackage"
export {default as BodyScrollPane} from "./packages/body-scroll-pane/BodyScrollPane"
export {default as SpellCheckPackage} from "./packages/spell-check/SpellCheckPackage"
export {default as SpellCheckManager} from "./packages/spell-check/SpellCheckManager"
export {default as SplitPanePackage} from "./packages/split-pane/SplitPanePackage"
export {default as SplitPane} from "./packages/split-pane/SplitPane"
export {default as ScrollbarPackage} from "./packages/scrollbar/ScrollbarPackage"
export {default as Scrollbar} from "./packages/scrollbar/Scrollbar"
export {default as LayoutPackage} from "./packages/layout/LayoutPackage"
export {default as Layout} from "./packages/layout/Layout"
export {default as ListPackage} from "./packages/list/ListPackage"
export {default as GridPackage} from "./packages/grid/GridPackage"
export {default as Grid} from "./packages/grid/Grid"
export {default as Dropzones} from "./packages/dropzones/Dropzones"
export {default as Overlay} from "./packages/overlay/Overlay"
export {default as TabbedPanePackage} from "./packages/tabbed-pane/TabbedPanePackage"
export {default as TabbedPane} from "./packages/tabbed-pane/TabbedPane"
export {default as ModalPackage} from "./packages/modal/ModalPackage"
export {default as Modal} from "./packages/modal/Modal"
export {default as InputPackage} from "./packages/input/InputPackage"
export {default as Input} from "./packages/input/Input"
export {default as ResponsiveApplication} from "./packages/responsive-application/ResponsiveApplication"
export {default as TOC} from "./packages/toc/TOC"
export {default as TOCProvider} from "./packages/toc/TOCProvider"
export {default as ToolDropdown} from "./packages/tools/ToolDropdown"
export {default as Tool} from "./packages/tools/Tool"
export {default as Toolbar} from "./packages/tools/Toolbar"
export {default as Toolbox} from "./packages/tools/Toolbox"
export {default as Surface} from "./packages/surface/Surface"
export {default as AbstractEditor} from "./ui/AbstractEditor"
export {default as AnnotationCommand} from "./ui/AnnotationCommand"
export {default as EditAnnotationCommand} from "./ui/EditAnnotationCommand"
export {default as AnnotationComponent} from "./ui/AnnotationComponent"
export {default as AnnotationTool} from "./ui/AnnotationTool"
export {default as BlockNodeComponent} from "./ui/BlockNodeComponent"
export {default as Command} from "./ui/Command"
export {Component}
export {default as ContainerEditor} from "./ui/ContainerEditor"
export {default as DragAndDropHandler} from "./ui/DragAndDropHandler"
export {default as DOMSelection} from "./ui/DOMSelection"
export {default as FontAwesomeIcon} from "./ui/FontAwesomeIcon"
export {default as InsertNodeCommand} from "./ui/InsertNodeCommand"
export {default as IsolatedNodeComponent} from "./packages/isolated-node/IsolatedNodeComponent"
export {default as Highlights} from "./ui/Highlights"
export {default as MacroManager} from "./ui/MacroManager"
export {default as NodeComponent} from "./ui/NodeComponent"
export {default as RenderingEngine} from "./ui/RenderingEngine"
export {default as Router} from "./ui/Router"
export {default as TextBlockComponent} from "./ui/TextBlockComponent"
export {default as TextPropertyComponent} from "./ui/TextPropertyComponent"
export {default as TextPropertyEditor} from "./ui/TextPropertyEditor"
export {default as UnsupportedNodeComponent} from "./ui/UnsupportedNodeComponent"
export {default as ArrayIterator} from "./util/ArrayIterator"
export {default as EventEmitter} from "./util/EventEmitter"
export {default as Factory} from "./util/Factory"
export {default as forEach} from "./util/forEach"
export {default as inBrowser} from "./util/inBrowser"
export {default as keys} from "./util/keys"
export {default as platform} from "./util/platform"
export {default as request} from "./util/request"
export {default as sendRequest} from "./util/sendRequest"
export {default as SubstanceError} from "./util/SubstanceError"
export {default as substanceGlobals} from "./util/substanceGlobals"
export {default as TreeIndex} from "./util/TreeIndex"
export {default as uuid} from "./util/uuid"
export {default as isArray} from "./util/isArray"
export {default as isArrayEqual} from "./util/isArrayEqual"
export {default as isBoolean} from "./util/isBoolean"
export {default as isEqual} from "./util/isEqual"
export {default as isFunction} from "./util/isFunction"
export {default as isNil} from "./util/isNil"
export {default as isNumber} from "./util/isNumber"
export {default as isObject} from "./util/isObject"
export {default as isPlainObject} from "./util/isPlainObject"
export {default as isString} from "./util/isString"
export {series} from "./util/async"
export {default as DefaultDOMElement} from "./dom/DefaultDOMElement"
export {default as BrowserDOMElement} from "./dom/BrowserDOMElement"
export {default as Configurator} from "./util/Configurator"

